name: Deploy to Production

on:
  push:
    branches: [pre-prod]
  pull_request:
    branches: [pre-prod]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: uses node.js with version ${{ secrets.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      # Set environment variables
      - name: Set environment variables
        run: |
          export DB_PROD_USERNAME=${{secrets.DB_PROD_USERNAME}}
          export DB_PROD_DIALECT=${{secrets.DB_PROD_DIALECT}}
          export DB_PROD_HOST=${{secrets.DB_PROD_HOST}}
          export DB_PROD_PASSWORD=${{secrets.DB_PROD_PASSWORD}}
          export DB_PROD_DATABASE=${{secrets.DB_PROD_DATABASE}}
          export DB_PROD_PORT=${{secrets.DB_PROD_PORT}}
          export NODE_ENV=production

      # Clone the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies and build the app
      - name: Install dependencies and build frontend + backend app
        run: |
          npm install
          CI=false npm run build:client
          CI=false npm run build:server

      # Start the server using PM2
      - name: Start server with PM2
        run: |
          sudo apt-get update
          npm install -g pm2
          sudo pm2 start npm --name kanban-server -- run start --workspace=kanban-server

      # Configure Nginx
      - name: Configure Nginx
        run: |
          echo "path-1:: ${PWD}"
          sudo apt-get install nginx
          sudo cp kanban.live.conf /etc/nginx/sites-available/kanban.live
          echo "path-2:: ${PWD}"
          sudo ln -s /etc/nginx/sites-available/kanban.live /etc/nginx/sites-enabled/
          echo "path-3:: ${PWD}"

      - name: Restart Nginx
        run: |
          echo "path-4:: ${PWD}"
          sudo systemctl restart nginx
          echo "path-5:: ${PWD}"

      # Clean up
      - name: Clean up
        run: |
          cd ../..
          rm -rf kanban-board
