name: Deploy to Production
"on":
  push:
    branches:
      - master
    pull-request:
      - master
jobs:
  runs-on: self-hosted
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: "uses node.js with version ${{ secrets.NODE_VERSION }}"
      uses: actions/setup-node@v1
      with:
        node-version: "${{ secrets.NODE_VERSION }}"

    - name: Install dependencies and build frontend + backend app
      run: |
        cd kanban-board
        npm install
        npm run build:client
        npm run build:server

    - name: Set environment variables
      run: |
        export DB_PROD_USERNAME=${{secrets.DB_PROD_USERNAME}}
        export DB_PROD_DIALECT=${{secrets.DB_PROD_DIALECT}}
        export DB_PROD_HOST=${{secrets.DB_PROD_HOST}}
        export DB_PROD_PASSWORD=${{secrets.DB_PROD_PASSWORD}}
        export DB_PROD_DATABASE=${{secrets.DB_PROD_DATABASE}}
        export DB_PROD_PORT=${{secrets.DB_PROD_PORT}}
        export NODE_ENV=production

    - name: Start server with PM2
      run: |
        sudo apt-get update
        npm install -g pm2
        pm2 start npm --name kanban-server -- run start --workspace=kanban-server
        pm2 startup
        pm2 save

    - name: Configure Nginx
      run: |
        sudo apt-get install nginx
        sudo cp kanban-board/kanban.live.conf /etc/nginx/sites-available/kanban.live
        sudo ln -s /etc/nginx/sites-available/kanban.live /etc/nginx/sites-enabled/
        sudo systemctl restart nginx

    - name: Clean up
      run: |
        rm -rf kanban-board
