name: Deploy to Production
on:
  push:
    branches: [main]
    pull-request: [main]
jobs:
  build:
    runs-on: self-hosted

  steps:
    # Clone the repository
    - name: Checkout code
      uses: actions/checkout@v2

    - name: uses node.js with version ${{ secrets.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ secrets.NODE_VERSION }}

    # Install dependencies and build the app
    - name: Install dependencies and build frontend + backend app
      run: |
        cd kanban-board
        npm install
        npm run build:client
        npm run build:server

    # Set environment variables
    - name: Set environment variables
      run: |
        export DB_PROD_USERNAME=${{secrets.DB_PROD_USERNAME}}
        export DB_PROD_DIALECT=${{secrets.DB_PROD_DIALECT}}
        export DB_PROD_HOST=${{secrets.DB_PROD_HOST}}
        export DB_PROD_PASSWORD=${{secrets.DB_PROD_PASSWORD}}
        export DB_PROD_DATABASE=${{secrets.DB_PROD_DATABASE}}
        export DB_PROD_PORT=${{secrets.DB_PROD_PORT}}
        export NODE_ENV=production

    # Start the server using PM2
    - name: Start server with PM2
      run: |
        sudo apt-get update
        npm install -g pm2
        pm2 start npm --name kanban-server -- run start --workspace=kanban-server

    # Configure Nginx
    - name: Configure Nginx
      run: |
        sudo apt-get install nginx
        sudo cp kanban-board/kanban.live.conf /etc/nginx/sites-available/kanban.live
        sudo ln -s /etc/nginx/sites-available/kanban.live /etc/nginx/sites-enabled/
        sudo systemctl restart nginx

    # Clean up
    - name: Clean up
      run: |
        rm -rf kanban-board
