name: Deploy to Production

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: uses node.js with version ${{ secrets.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      # Clone the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies and build the app
      - name: Install dependencies and build frontend + backend app
        run: |
          npm install
          CI=false npm run build:client
          CI=false npm run build:server

      - name: Create .env file
        run: |
          touch .env
          echo DB_PROD_USERNAME=${{ secrets.DB_PROD_USERNAME }} >> .env
          echo DB_PROD_DIALECT=${{ secrets.DB_PROD_DIALECT }} >> .env
          echo DB_PROD_DIALECT=${{ secrets.DB_PROD_DIALECT }} >> .env
          echo DB_PROD_PASSWORD=${{ secrets.DB_PROD_PASSWORD }} >> .env
          echo DB_PROD_DATABASE=${{ secrets.DB_PROD_DATABASE }} >> .env
          echo DB_PROD_PORT=${{ secrets.DB_PROD_PORT }} >> .env
          echo NODE_ENV="production" >> .env

      - name: Install pm2
        run: |
          npm install -g pm2

      # start the server
      - name: Start the server
        run: |
          pm2 delete kanban-server || true
          pm2 start npm --name kanban-server -- run start --workspace=kanban-server
          pm2 save

      # Configure Nginx
      - name: Configure Nginx
        run: |
          cd ~
          echo ${{ secrets.SUDO_PASSWORD }} | sudo -S rm -f -- /etc/nginx/sites-available/kanban.live
          echo ${{ secrets.SUDO_PASSWORD }} | sudo -S rm -f -- /etc/nginx/sites-enabled/kanban.live

          sudo systemctl enable nginx

          sudo cp /home/kanbanuser/app/_work/kanban-board/kanban-board/kanban.live.conf /etc/nginx/sites-available/kanban.live
          sudo ln -s /etc/nginx/sites-available/kanban.live /etc/nginx/sites-enabled/

      - name: Restart Nginx
        run: |
          echo ${{ secrets.SUDO_PASSWORD }} | sudo -S systemctl restart nginx
