name: Deploy to Production

on:
  push:
    branches: [deploy]
  pull_request:
    branches: [deploy]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: uses node.js with version ${{ secrets.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      # Clone the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies and build the app
      - name: Install dependencies and build frontend + backend app
        run: |
          echo "path-1:: $GITHUB_WORKSPACE"
          npm install
          CI=false npm run build:client
          CI=false npm run build:server

      - name: Create .env file
        run: |
          touch .env
          echo DB_PROD_USERNAME=${{ secrets.DB_PROD_USERNAME }} >> .env
          echo DB_PROD_DIALECT=${{ secrets.DB_PROD_DIALECT }} >> .env
          echo DB_PROD_DIALECT=${{ secrets.DB_PROD_DIALECT }} >> .env
          echo DB_PROD_PASSWORD=${{ secrets.DB_PROD_PASSWORD }} >> .env
          echo DB_PROD_DATABASE=${{ secrets.DB_PROD_DATABASE }} >> .env
          echo DB_PROD_PORT=${{ secrets.DB_PROD_PORT }} >> .env
          echo NODE_ENV="production" >> .env

      - name: Install pm2
        run: |
          npm install -g pm2

      # added the Startup Script to the system
      - name: Add Startup Script
        run: |
          sudo env PATH=$PATH:/home/kanbanuser/app/_work/_tool/node/18.16.0/x64/bin /home/kanbanuser/app/_work/_tool/node/18.16.0/x64/lib/node_modules/pm2/bin/pm2 startup systemd -u kanbanuser --hp /home/kanbanuser

      # start the server
      - name: Start the server
        run: |
          cd $GITHUB_WORKSPACE
          pm2 start npm --name kanban-server -- run start --workspace=kanban-server
          echo "path-2:: $GITHUB_WORKSPACE"
          pm2 save

      # Configure Nginx
      - name: Configure Nginx
        run: |
          cd ~
          sudo rm -f -- /etc/nginx/sites-available/kanban.live
          sudo rm -f -- /etc/nginx/sites-enabled/kanban.live

          sudo systemctl enable nginx

          sudo cp /home/kanbanuser/app/_work/kanban-board/kanban-board/kanban.live.conf /etc/nginx/sites-available/kanban.live
          sudo ln -s /etc/nginx/sites-available/kanban.live /etc/nginx/sites-enabled/

      - name: Print env test
        run: echo $DB_PROD_USERNAME

      - name: Restart Nginx
        run: |
          sudo systemctl restart nginx
