name: Deploy to Production

on:
  push:
    branches: [pre-prod]
  pull_request:
    branches: [pre-prod]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: uses node.js with version ${{ secrets.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      # Set environment variables
      - name: Set environment variables
        run: |
          export DB_PROD_USERNAME=${{secrets.DB_PROD_USERNAME}}
          export DB_PROD_DIALECT=${{secrets.DB_PROD_DIALECT}}
          export DB_PROD_HOST=${{secrets.DB_PROD_HOST}}
          export DB_PROD_PASSWORD=${{secrets.DB_PROD_PASSWORD}}
          export DB_PROD_DATABASE=${{secrets.DB_PROD_DATABASE}}
          export DB_PROD_PORT=${{secrets.DB_PROD_PORT}}
          export NODE_ENV=production

      # Clone the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies and build the app
      - name: Install dependencies and build frontend + backend app
        run: |
          npm install
          CI=false npm run build:client
          CI=false npm run build:server

      # Start the server using PM2
      # check if any process running found delete them
      - name: Start server with PM2
        run: |
          sudo apt-get update
          npm install -g pm2

      # added the Startup Script to the system
      - name: Add Startup Script
        run: |
          sudo env PATH=$PATH:/home/kanban/_work/_tool/node/18.16.0/x64/bin /home/kanban/_work/_tool/node/18.16.0/x64/lib/node_modules/pm2/bin/pm2 startup systemd -u kanban --hp /home/kanban

      # start the server
      - name: Start the server
        run: |
          echo "path-1:: ${PWD}"
          pm2 start npm --name kanban-server -- run start --workspace=kanban-server
          echo "path-2:: $GITHUB_WORKSPACE"
          pm2 save
          echo "path-3:: $GITHUB_WORKSPACE"

      # Configure Nginx
      - name: Configure Nginx
        run: |
          cd~
          sudo apt-get install nginx

          if [ -f /etc/nginx/sites-available/kanban.live ]; then
          sudo rm /etc/nginx/sites-available/kanban.live; fi

          if [ -f /etc/nginx/sites-enabled/kanban.live ]; 
          then sudo rm /etc/nginx/sites-enabled/kanban.live; fi

          sudo systemctl enable nginx

          sudo cp /home/runner/work/kanban-board/kanban-board/kanban.live.conf /etc/nginx/sites-available/kanban.live
          sudo ln -s /etc/nginx/sites-available/kanban.live /etc/nginx/sites-enabled/

      - name: Restart Nginx
        run: |
          sudo systemctl restart nginx
